version: '3.7'

services:
  mqtt_broker:
    image: eclipse-mosquitto:2
    volumes:
      - ./config/:/mosquitto/config/:ro
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - my_network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - my_network

  kafka:
    image: confluentinc/cp-kafka:6.1.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - my_network

  iot_data_generator:
    build: ./iot_data_generator
    environment:
      - MQTT_HOST=mqtt_broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=sensors
      - INTERVAL_MS=1000
      - LOGGING_LEVEL=20
    depends_on:
      - mqtt_broker
    networks:
      - my_network
  
  iot_data_processor:
    build: ./iot_data_processor
    environment:
      - MQTT_HOST=mqtt_broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=sensors
      - LOGGING_LEVEL=20
    depends_on:
      - iot_data_generator
      - mqtt_broker
    networks:
      - my_network
  
  iot_kafka_producer:
    build: ./iot_kafka_producer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=sensors
      - MQTT_HOST=mqtt_broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=sensors
      - LOGGING_LEVEL=20
    depends_on:
      - mqtt_broker
      - iot_data_generator
      - kafka
    networks:
      - my_network

volumes:
  data: ~

networks:
  my_network:
  